export interface State {
  name: string;
}

export interface Country {
  name: string;
  flag: string;
  states: State[];
}

export const geography: Country[] = [
  {
    name: "Nigeria",
    flag: "🇳🇬",
    states: [
      { name: "Abia" },
      { name: "Adamawa" },
      { name: "Akwa Ibom" },
      { name: "Anambra" },
      { name: "Bauchi" },
      { name: "Bayelsa" },
      { name: "Benue" },
      { name: "Borno" },
      { name: "Cross River" },
      { name: "Delta" },
      { name: "Ebonyi" },
      { name: "Edo" },
      { name: "Ekiti" },
      { name: "Enugu" },
      { name: "FCT - Abuja" },
      { name: "Gombe" },
      { name: "Imo" },
      { name: "Jigawa" },
      { name: "Kaduna" },
      { name: "Kano" },
      { name: "Katsina" },
      { name: "Kebbi" },
      { name: "Kogi" },
      { name: "Kwara" },
      { name: "Lagos" },
      { name: "Nasarawa" },
      { name: "Niger" },
      { name: "Ogun" },
      { name: "Ondo" },
      { name: "Osun" },
      { name: "Oyo" },
      { name: "Plateau" },
      { name: "Rivers" },
      { name: "Sokoto" },
      { name: "Taraba" },
      { name: "Yobe" },
      { name: "Zamfara" },
    ],
  },
  {
    name: "Ghana",
    flag: "🇬🇭",
    states: [
      { name: "Ashanti" },
      { name: "Brong-Ahafo" },
      { name: "Central" },
      { name: "Eastern" },
      { name: "Greater Accra" },
      { name: "Northern" },
      { name: "Upper East" },
      { name: "Upper West" },
      { name: "Volta" },
      { name: "Western" },
    ],
  },
  {
    name: "Niger",
    flag: "🇳🇪",
    states: [
      { name: "Agadez" },
      { name: "Diffa" },
      { name: "Dosso" },
      { name: "Maradi" },
      { name: "Tahoua" },
      { name: "Tillabéri" },
      { name: "Zinder" },
    ],
  },
  {
    name: "Benin",
    flag: "🇧🇯",
    states: [
      { name: "Alibori" },
      { name: "Atakora" },
      { name: "Atlantique" },
      { name: "Borgou" },
      { name: "Collines" },
      { name: "Donga" },
      { name: "Kouffo" },
      { name: "Littoral" },
      { name: "Mono" },
      { name: "Ouémé" },
      { name: "Plateau" },
      { name: "Zou" },
    ],
  },
  {
    name: "Tanzania",
    flag: "🇹🇿",
    states: [
      { name: "Arusha" },
      { name: "Dar es Salaam" },
      { name: "Dodoma" },
      { name: "Geita" },
      { name: "Iringa" },
      { name: "Kagera" },
      { name: "Katavi" },
      { name: "Kigoma" },
      { name: "Kilimanjaro" },
      { name: "Lindi" },
      { name: "Manyara" },
      { name: "Mara" },
      { name: "Mbeya" },
      { name: "Morogoro" },
      { name: "Mtwara" },
      { name: "Mwanza" },
      { name: "Njombe" },
      { name: "Pwani" },
      { name: "Rukwa" },
      { name: "Ruvuma" },
      { name: "Shinyanga" },
      { name: "Simiyu" },
      { name: "Singida" },
      { name: "Tabora" },
      { name: "Tanga" },
    ],
  },
  {
    name: "Egypt",
    flag: "🇪🇬",
    states: [
      { name: "Alexandria" },
      { name: "Aswan" },
      { name: "Asyut" },
      { name: "Beheira" },
      { name: "Beni Suef" },
      { name: "Cairo" },
      { name: "Dakahlia" },
      { name: "Damietta" },
      { name: "Faiyum" },
      { name: "Gharbia" },
      { name: "Giza" },
      { name: "Ismailia" },
      { name: "Kafr El Sheikh" },
      { name: "Luxor" },
      { name: "Matrouh" },
      { name: "Minya" },
      { name: "Monufia" },
      { name: "New Valley" },
      { name: "North Sinai" },
      { name: "Port Said" },
      { name: "Qalyubia" },
      { name: "Qena" },
      { name: "Red Sea" },
      { name: "Sharqia" },
      { name: "Sohag" },
      { name: "South Sinai" },
      { name: "Suez" },
    ],
  },
  {
    name: "Morocco",
    flag: "🇲🇦",
    states: [
      { name: "Béni Mellal-Khénifra" },
      { name: "Casablanca-Settat" },
      { name: "Drâa-Tafilalet" },
      { name: "Fès-Meknès" },
      { name: "Guelmim-Oued Noun" },
      { name: "Laâyoune-Sakia El Hamra" },
      { name: "Marrakech-Safi" },
      { name: "Oriental" },
      { name: "Rabat-Salé-Kénitra" },
      { name: "Souss-Massa" },
      { name: "Tanger-Tétouan-Al Hoceïma" },
    ],
  },
  {
    name: "South Africa",
    flag: "🇿🇦",
    states: [
      { name: "Eastern Cape" },
      { name: "Free State" },
      { name: "Gauteng" },
      { name: "KwaZulu-Natal" },
      { name: "Limpopo" },
      { name: "Mpumalanga" },
      { name: "North West" },
      { name: "Northern Cape" },
      { name: "Western Cape" },
    ],
  },
  {
    name: "United Kingdom",
    flag: "🇬🇧",
    states: [
      { name: "England" },
      { name: "Scotland" },
      { name: "Wales" },
      { name: "Northern Ireland" },
    ],
  },
  {
    name: "United States",
    flag: "🇺🇸",
    states: [
      { name: "Alabama" },
      { name: "Alaska" },
      { name: "Arizona" },
      { name: "Arkansas" },
      { name: "California" },
      { name: "Colorado" },
      { name: "Connecticut" },
      { name: "Delaware" },
      { name: "Florida" },
      { name: "Georgia" },
      { name: "Hawaii" },
      { name: "Idaho" },
      { name: "Illinois" },
      { name: "Indiana" },
      { name: "Iowa" },
      { name: "Kansas" },
      { name: "Kentucky" },
      { name: "Louisiana" },
      { name: "Maine" },
      { name: "Maryland" },
      { name: "Massachusetts" },
      { name: "Michigan" },
      { name: "Minnesota" },
      { name: "Mississippi" },
      { name: "Missouri" },
      { name: "Montana" },
      { name: "Nebraska" },
      { name: "Nevada" },
      { name: "New Hampshire" },
      { name: "New Jersey" },
      { name: "New Mexico" },
      { name: "New York" },
      { name: "North Carolina" },
      { name: "North Dakota" },
      { name: "Ohio" },
      { name: "Oklahoma" },
      { name: "Oregon" },
      { name: "Pennsylvania" },
      { name: "Rhode Island" },
      { name: "South Carolina" },
      { name: "South Dakota" },
      { name: "Tennessee" },
      { name: "Texas" },
      { name: "Utah" },
      { name: "Vermont" },
      { name: "Virginia" },
      { name: "Washington" },
      { name: "West Virginia" },
      { name: "Wisconsin" },
      { name: "Wyoming" },
    ],
  },
  {
    name: "United Arab Emirates",
    flag: "🇦🇪",
    states: [
      { name: "Abu Dhabi" },
      { name: "Ajman" },
      { name: "Dubai" },
      { name: "Fujairah" },
      { name: "Ras Al Khaimah" },
      { name: "Sharjah" },
      { name: "Umm Al Quwain" },
    ],
  },
];
